import Head from 'next/head'
import Form from '../components/Form/Form'

export default function Home() {
  return (
    <div className="px-8 mt-10">
      <Head>
        <title>axenso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-200 mx-auto">
        <h1 className="t2">Seminar Registration</h1>
        <div>
          <Form />
        </div>
      </main>

    </div>
  )
}
