import Head from 'next/head'
import Form from '../components/Form/Form'

export default function Home() {
  return (
    <div className="px-8 mt-10">
      <Head>
        <title>axenso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto">
        <h1 className="text-4xl font-bold">
          <span className="text-white">Seminar</span> <span className="text-blue-600">Registration</span>
        </h1>
        <div className="flex justify-center md:mt-10">
          <Form />
        </div>
      </main>

    </div>
  )
}
