import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Step1 from '../components/SelectBox'
import Step2 from '../components/RadioBox'
import Step3 from '../components/CheckBox'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>axenso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Step1 />
      <Step2 />
      <Step3 />
    </div>
  )
}
